/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.tahar;

import dev.tahar.puzzle.day.five.DayFive;
import dev.tahar.puzzle.day.four.DayFour;
import dev.tahar.puzzle.day.one.DayOne;
import dev.tahar.puzzle.day.seven.DaySeven;
import dev.tahar.puzzle.day.six.DaySix;
import dev.tahar.puzzle.day.ten.DayTen;
import dev.tahar.puzzle.day.three.DayThree;
import dev.tahar.puzzle.day.two.DayTwo;

import java.util.List;

public class App {

    public static void main(String[] args) {
        final var days = List.of(
                new DayOne(),
                new DayTwo(),
                new DayThree(),
                new DayFour(),
                new DayFive(),
                new DaySix(),
                new DaySeven(),
                new DayTen());

        for (int i = 0; i < days.size(); ++i) {
            final var day = days.get(i);

            System.out.printf("=== Day %d: %s ===\n", i + 1, day.getTitle());
            System.out.printf("1)\t%s\n", day.executePartOne());
            System.out.printf("2)\t%s\n\n", day.executePartTwo());
        }
    }

}
